### ISSUE TITLE
Landing Page: Add list view for polls

### ISSUE THREAD

**Issue by emsbe** [pollmelo/fruitend#11]
As a user, I'd like to see all existing polls when accessing the application, in order to use the main functionality: voting in polls.

Based on issue #1 and the "Add New Poll" epic (issues #5, #7, #8, #9, #10).

---

### :thought_balloon: &nbsp; Hints & Thoughts
See the [wireframe mockup on Figma](https://www.figma.com/proto/ZrbrdOSBGLSMt1hjgjTvWA/Pollmelo?node-id=2006%3A17&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=2003%3A3)
The current prototype shows a placeholder for a profile picture to show the user who created the poll. This functionality can most likely not be added right now.

In future, when clicking on the title of a poll, a new page will open that only shows the selected poll. This functionality will be added in a future issue. In this issue, the information collected from the database will just get displayed.

---

## :white_check_mark: &nbsp; Conditions of satisfaction

- [ ] should list the first 10 polls in the response after making a get-request to the database
- [x] should display each poll in its own box outlined in #E95829 with the title in bold, the description in regular below, the end date with the prefix "endet am" on the bottom left as well the number of up and down votes below "thumb up" and "thumb down" symbol on the bottom right
- [x] the background surrounding the list view should be #EBEBEB
- [x] should display the state (active or closed) on the top right: a green circle for an open poll, a red circle for a closed poll

**Comment by martincodes-de** [comment]
@emsbe should the date have leading zeros?

**Comment by emso-sp** [comment]
> @emsbe should the date have leading zeros?

@martincodes-de Yes, dates with leading zeros look more clean in my opinion.
