### ISSUE TITLE
Create about Page

### ISSUE THREAD

**Issue by GrafBunsen** [pollmelo/fruitend#30]
An about page is linked to in the nav bar, but doesnt exist jet. It has not yet been desinged so the design is part of the issue. It should at least link the github organisation

**Comment by martincodes-de** [comment]
idea: add our names and circumstances why we created the project, how its done, linking our paper, github, ... + pictures of us (@NiklasBGit's idea)

**Comment by GrafBunsen** [comment]
no picture and name for me please
