### ISSUE TITLE
Create New Poll: Add calendar view to select end date

### ISSUE THREAD

**Issue by emso-sp** [pollmelo/fruitend#8]
As a user, I'd like to have a calendar view when selecting the end date of the poll, in order to simplify the selection process.

Based on issue #5 and issue #7

---

### :thought_balloon: &nbsp; Hints & Thoughts
See the [wireframe mockup on Figma](https://www.figma.com/proto/ZrbrdOSBGLSMt1hjgjTvWA/Pollmelo?node-id=2006%3A17&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=2003%3A3)

---

## :white_check_mark: &nbsp; Conditions of satisfaction

- [ ] should show a small popup window when clicking on the appropriate field to select the end date
- [ ] should allow the user to select a different month via a drop-down menu
- [ ] should add the selected end date to the form when clicking on a date in the calendar view
- [ ] pop-up window should close automatically when selecting a date
- [ ] pop-up window should close when clicking somewhere else on the page

**Comment by GrafBunsen** [comment]
this came automatically with the form and thus is part of #23
