### ISSUE TITLE
Create New Poll: Add submit button

### ISSUE THREAD

**Issue by emso-sp** [pollmelo/fruitend#9]
As a user, I'd like to be able to submit a newly created poll, in order to publish it and make it accessible to other users.

Based on issue #5, #7 and #8

---

### :thought_balloon: &nbsp; Hints & Thoughts
See the [wireframe mockup on Figma](https://www.figma.com/proto/ZrbrdOSBGLSMt1hjgjTvWA/Pollmelo?node-id=2006%3A17&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=2003%3A3)

---

## :white_check_mark: &nbsp; Conditions of satisfaction

- [ ] button should be coloured in #E5CB86 with a text in #D56528 reading "Veröffentlichen"
- [ ] should trigger a put call to the backend in order to add the poll to the database
- [ ] should inform the user of the outcome of the communication with the backend: If the poll was successfully added to the database, print an affirmative message on the page. If not, it should inform the user via an error message.
- [ ] when writing to the database fails, all form input should still be there for the user to retry submitting the poll (form should not be erased)

**Comment by GrafBunsen** [comment]
done as part of #23
